"""Feature groups — one module per group. Importing this package self-registers every group.

To add a feature, add ONE module here decorated with ``@register`` and import it below. No edits to
base/registry/engine/store/parity/introspect (FEATURE_PLATFORM.md §3.7).
"""
from quantlib.features.groups import (  # noqa: F401
    asset_flags,
    breadth,
    calendar,
    calendar_events,
    candlestick,
    clean_momentum,
    cross_sectional_rank,
    daily_beta,
    distribution,
    dumper_state,
    efficiency,
    gap_fill_state,
    inter_arrival,
    intraday_seasonality,
    liquidity,
    liquidity_rank,
    market_beta,
    market_context,
    microstructure_burst,
    momentum,
    momentum_consistency,
    momentum_run,
    multi_day,
    multi_day_vwap,
    ohlc_vol,
    overnight_beta,
    overnight_intraday_split,
    peer_relative,
    price_levels,
    price_returns,
    price_volume,
    prior_day,
    quote_spread,
    residual_analysis,
    return_dispersion,
    return_dynamics,
    round_levels,
    runner_state,
    sector,
    signed_trade_ratio,
    swing,
    technical,
    tick_runlength,
    trade_flow,
    trade_freq_z,
    trade_size_dist,
    trend_quality,
    volatility,
    volume,
    volume_exhaustion,
)
