"""Residual-analysis features: the distribution of close around its linear trend (family: TREND_QUALITY, Layer A).

These extend ``trend_quality`` (the OLS slope/R^2 exemplar) from "is price trending" to "is the move CLEAN":
small, symmetric residuals around the fitted line are a tradeable straight-line move; large residuals are chop
dressed up as a trend. The fit is the SAME trailing OLS of close on a frame-relative time axis ``trend_quality``
uses (residuals are origin-invariant).

``residual_std`` is the std of the OLS residuals as a percent of mean price. It is a closed form of the SAME six
paired OLS sums ``trend_quality`` declares (b, x, y, xy, xx, yy): ``Σr² = Syy_c − slope·Sxy_c`` (centered sums),
``residual_std = sqrt(Σr²/n)/mean_close·100``. So this is a windowed REDUCTION group — it declares the same OLS
regression and reads the shared ``resid_std`` OLS stat the reduction kernel computes from those sums (the §7
Lever-2 migration: it now rides the shared marshal + Rust ``assemble_canonical`` instead of a per-minute
``rolling_sum_by(...).over("symbol")``). Centering the time axis on the frame's earliest minute keeps the sums
well-conditioned, so the difference-of-sums stays accurate even for a near-perfect fit.

The group ships ONLY ``residual_std`` (the 2nd-moment residual dispersion). The old ``residual_mean_abs`` /
``residuals_symmetric`` features were dropped (2026-06-15): the OLS mean residual is identically 0 by
construction, so ``residual_mean_abs`` was a hard-coded constant ``0.0`` and ``residuals_symmetric`` (derived as
``mean_abs < 0.1``) was a constant ``1.0`` — 12 of 18 columns carried zero information (dead features). A genuine
residual-ASYMMETRY feature (signed third moment of the residuals) needs additional power sums (x^2·y, x^3, …)
that this group does not accumulate; it is a modeller feature-design task, tracked alongside ``momentum_run``'s
residual skew.

Parity: the ``resid_std`` OLS stat uses the EXACT centered-sum algebra the former hand-written group used, so the
catastrophic-cancellation difference of two nearly-equal sums rounds identically across the polars / numpy / Rust
twins (``_ols_stat_exprs`` / ``_ols_stat_numpy`` / ``assemble_canonical`` kind 7). ``compute()`` and
``compute_latest()`` are generated by ``ReductionGroup`` and ride the SAME ``assemble()``, guarded cell-for-cell
by tests/test_fp_latest.py. The degenerate near-linear cutoff (``REL_RESID_FLOOR``) and the ``MIN_POINTS`` floor
are baked into the shared stat so backfill and live agree by construction. ``incremental_safe=False``: the SSR is
the same near-perfect-fit cancellation as ``price_r2`` — it stays on the batch fresh-sum path until the
centered-sum stabilisation (Lever-1) lands. residual SKEW (the third moment) lives in ``momentum_run``.
"""
from __future__ import annotations

import polars as pl

from quantlib.features.base import (
    FeatureSpec,
    FeatureType,
    InputSpec,
)
from quantlib.features.declarative import ReductionGroup, StatefulRegressor, resid_std_
from quantlib.features.registry import register

WINDOWS: tuple[int, ...] = (5, 10, 15, 20, 30, 60)
RESID_TOL = 1e-4


@register
class ResidualAnalysisGroup(ReductionGroup):
    name = "residual_analysis"
    # 1.1.0: migrated to a ReductionGroup (the OLS residual-std rides the shared reduction kernel via the new
    # resid_std OLS stat) — value-identical to the 1.0.0 hand-written rolling form (same centered-sum algebra).
    version = "1.1.0"
    owner = "modeller"
    type = FeatureType.TREND_QUALITY
    inputs = (InputSpec(name="minute_agg", columns=("symbol", "minute", "close")),)
    # The SSR is a difference of large near-equal centered power sums on a near-perfect intraday fit (the same
    # cancellation as price_r2's n==2 corner), so the incremental running add/subtract sums round differently
    # from the batch fresh window sums past the parity-breach ratio. Stay on the batch fresh-sum path until the
    # centered-sum stabilisation (Lever-1) lands; the absolute divergence is ~float-floor (a self-check guard).
    incremental_safe = False

    def declare(self) -> list[FeatureSpec]:
        return [
            FeatureSpec(
                name=f"residual_std_{w}m",
                description=f"Std of OLS residuals around the {w}-minute close-vs-time trend, as a percent of mean price: how tightly price hugs its trend line.",
                dtype="Float64",
                valid_range=(0.0, 100.0),
                nan_policy="warmup",
                layer="A",
                tolerance=RESID_TOL,
            )
            for w in WINDOWS
        ]

    def regressions(self) -> dict[str, tuple[pl.Expr, pl.Expr, tuple[str, ...], tuple[int, ...]]]:
        epoch = pl.col("minute").dt.epoch("s").cast(pl.Float64)
        centered_t = (epoch - epoch.min()) / 60.0  # frame-relative time regressor (OLS is origin-invariant)
        return {"resid": (centered_t, pl.col("close"), ("resid_std",), WINDOWS)}

    def stateful_regressors(self) -> dict[str, list[StatefulRegressor]]:
        return {"resid": [StatefulRegressor(slot="x", kind="time")]}

    def assemble(self) -> dict[str, pl.Expr]:
        return {f"residual_std_{w}m": resid_std_("resid", w) for w in WINDOWS}
